#! /usr/bin/env python
import shutil
import os

from app import db
from app.mod_articles.models import Article
import app.mod_articles as _articles

last_article = Article.query.all()[-1]

if input(f'Delete {last_article.name}? [y/N] ').lower() != 'y':
    print('Exiting without deletion')
    exit(0)

category = last_article.category
name = last_article.name

# Get rid of the directory for images.
shutil.rmtree(
    _articles.article_images_dir_path(category, name, remote=False)
)

# And the article itself.
article_path = os.path.join(
    _articles.article_category_path(category, remote=False),
    f'{name}.html',
)
os.unlink(article_path)

# Remove the record.
db.session.delete(last_article)
db.session.commit()
